### ISSUE TITLE
radar seems broken

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/gameplay#1]
I'm not able to see anything more while wearing a radar.

How to reproduce:

```
/devmap plat23
/team humans; give funds 10000 ; give momentum 10000
- join -
- buy a radar -
/bot add * aliens
/bot add * aliens
/bot add * aliens
```

**Comment by Viech** [comment]
Just to be clear, we have ruled out the possiblity that there is a bug?

**Comment by Gireen** [comment]
There is a bug in the radar Unvanquished/Unvanquished#1169
But that is not related to this issue. 

from radar seems broken to radar is op without doing anything, i like that 😄
I think this issue is solved with that and with the suggested changes from #3 
🎉

**Comment by Viech** [comment]
Alright so I'll close this one as it was originally about a bug and because we seem to have accepted the notion that the radar is currently too strong in #3.
