### ISSUE TITLE
Alien team damage is really high and this (IMO) breaks teamfight

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/gameplay#10]
Evolved aliens (not dretch) have a hard time fighting together. While the dretch can't receive team damage, anything bigger than that will suffer heavily from it. Let's see a few examples.

As a marauder jumping around on the the USS Tremor map, I take the direct path to the human base. That's a very busy path when bots are playing. I notice an human, engage and try to hit it. A mantis leaps forward and I unfortunately hit it. The poor creature takes 40 damages, which is half its health. The humans then make a successful shotgun hit and the mantis is dead.

As an advanced dragoon fighting on spacetracks, I'm in the long corridor on top of the stairs trying to damage some human in heavy armor. Those are really fearsome and hard enough to kill even when they are bots, so I'm just trying to barb it while dodging the plasma blasts. A mantis jumps into the fight and end up right in front of the human. Despite being full hp, it is instantly killed by the 100 dmg projectile. That is to be be compared with the 22hp the human would have lost, the fairly high chances the human has to dodge it, and the very few (3) projectiles the alien has. I found that very sad.

As an advanced marauder again, I try to assist some dragoon in a fight. Since the human is dancing, I end up hitting the dragoon twice (the adv marauder attack is very fast). That means I backstabbed my ally removing it 80hp.

Another day, as tyrant, I try to help a marauder, … Actually you probably know what happened already. Just in case: I removed two thirds of the marauder's hp, killing it.

I find this really frustrating. It's hard enough for aliens to play together, because they need to be in the same place because they need to be in contact with the same enemy.

Maybe we could have a ¼ damage multiplier for alien team damage? Maybe shots that would hit an allied creature (not building) should be blocked (think "you can't because the hivemind wouldn't stab itself") ? What do you think?

**Comment by Viech** [comment]
I agree and I think this was never intended like this but merely a side effect of how humans and aliens have different damage and health/armor values. In particular alien forms have a high range of health values to balance their different sizes. Human team damage, in comparison, is reduced.

With the new entity system, it would be easy to have damage multipliers for team damage which could even distinguish between buildables and players if we felt that's necessary.
