### ISSUE TITLE
Granger spit should not damage friendly buildings

### ISSUE THREAD

**Issue by slipher** [Unvanquished/gameplay#22]
Granger spit can be used to put out fires on alien buildables. So it doesn't make much sense that the healing granger spit also damages alien buildables.

**Comment by necessarily-equal** [comment]
Unless we decide on some mending, this is fixed by https://github.com/Unvanquished/Unvanquished/pull/1947

**Comment by necessarily-equal** [comment]
Closing. If someone wants to give granger spit healing properties, please open an issue
