### ISSUE TITLE
[Problem] granger's lockblob is too powerful

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/gameplay#48]
Advanced granger blob received the "lock" feature in 0.52. This makes grangers able to lock humans, as long as they're not wearing a battlesuit.
Grangers are *builders*, an utility class, but this makes them very dangerous in battle, and this is *for free*, as advanced grangers cost 0¤.

In duel, they are able to easily defeat a human with a jetpack, a medium armor and a pulse rifle, which have a total cost of 870¤. In the case the human wins, after struggling a lot since their enemy can wallwalk, they only get rewarded 200¤.

While I am not against allowing grangers to defend themselves a bit, this features is way too powerful considering the cost for both sides.

**Disclaimer**
>All problems issues are treated as opinions until agree upon

**Comment by Gireen** [comment]
i would agree to the title but not that it is too easy to kill with the adv granger.

what is with a naked rifle player? should a adv granger be able to kill it with skill?
both are free but the alien is a later stage unit.

and lets compare grangers with human builders.
can a human with blaster kill a dretch with skill? 
the answer is yes definitive.  

and what is with later stage human builders with armor. a dretch becomes less and less usable against human builders.
compared to a slow granger which strongest attack is melee 

so there is a big power difference between human and alien builders in favor of humans and the lockblob is there to even out the playing field a bit. i admit that equipment should play a bigger role in the effectiveness of it

**Comment by cu-kai** [comment]
> and lets compare grangers with human builders.
can a human with blaster kill a dretch with skill?
the answer is yes definitive.

I wouldn't be against buffing the granger's claw slightly, particularly in the case of headshots vs non-armoured humans.

**Comment by bmorel** [comment]
This has been fixed.
