### ISSUE TITLE
[Idea] Reward credits for destroying buildings

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/gameplay#50]
Related Problem issues: 

Currently, the game only gives momentum when one destroys buildings, which encourages to camp (because, why attack to loose armour and weapons?).
Players complain about this on a regular basis.

Giving some credits when you destroy buildings would probably help encouraging attacking. It might also discourage forward building, though.

**Disclaimer**
>Ideas without a related problem issue and lacking explanation or depth are closed after a certain time.

**Comment by DolceTriade** [comment]
I think we've heard this enough from many players that it deserves to be experimented with
