### ISSUE TITLE
Increase flamer damage 5→8, floor fire chance 0.1→0.2, reduce range to that of the acid tube

### ISSUE THREAD

**Issue by mjstahlberg** [Unvanquished/gameplay#69]
Related Problem issues: #51

The flamer was nerfed last year as follows:

- damage 10 (→ 2) → 5
- ignite chance 0.5 → 0.2
- floor fire chance 0.3 → 0.1

I could come up with the following compromise with @illwieckz:

- damage 5 → 8
- (ignite chance remains at 0.2)
- floor fire chance 0.1 → 0.2
- the range is reduced such that an acid tube can hit back (ca. 20%, will report the exact value later)

**This comprimse was difficult to reach,** so while this issue is open to discussion in theory, I'd strongly prefer if y'all would just agree to it with a thumbs up if this proposal is at all acceptable to you, so that we can take some immediate action to get the flamer back into the game. This doesn't have to be the last balance change, just a starting point to find a middle ground between the initial OP and the current UP states.

**Comment by DolceTriade** [comment]
:shrug: I think additional changes for flamer are required. I'm not convinced this is enough to bring the flamer back into the game, but the flamer is quite weak so this buff is fine.

**Comment by mjstahlberg** [comment]
Having tested the flamer yesterday a bit, I tend to agree, but let's do these changes first and re-evaluate from there. I've talked to @illwieckz on IRC and he'd be fine with the two buffs also without the range nerf; so I'll PR only the two buffs for now.
